/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ColumnsFilter: typeof import('./src/components/ColumnsFilter.vue')['default']
    ContractsTable: typeof import('./src/components/ContractsTable.vue')['default']
    DateInput: typeof import('./src/components/DateInput.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    OrderByInput: typeof import('./src/components/OrderByInput.vue')['default']
    PayType: typeof import('./src/components/PayType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    ShowPaysInput: typeof import('./src/components/ShowPaysInput.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TableComponent: typeof import('./src/components/Table/TableComponent.vue')['default']
    TableDolar: typeof import('./src/components/TableDolarFacturados.vue')['default']
    TableDolarFacturados: typeof import('./src/components/TableDolarFacturados.vue')['default']
    TableFacturados: typeof import('./src/components/TableFacturados.vue')['default']
    TBodyComponent: typeof import('./src/components/Table/TBodyComponent.vue')['default']
    THeadersComponent: typeof import('./src/components/Table/THeadersComponent.vue')['default']
    TransactionInput: typeof import('./src/components/TransactionInput.vue')['default']
    Transactions: typeof import('./src/components/Transactions.vue')['default']
    TransactionsSpace: typeof import('./src/components/TransactionsSpace.vue')['default']
    TransactionsTable: typeof import('./src/components/TransactionsTable.vue')['default']
    TypeReport: typeof import('./src/components/TypeReport.vue')['default']
  }
}
